version: '3'

services:
  db:
    image: postgres
    env_file: ./.env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./.docker/redis:/var/lib/redis/data
  web:
    build: .
    env_file: ./.env
    command: npm run server
    links:
      - redis
    ports:
      - "80:80"
    depends_on:
      - db
